#pragma once

enum SIMON_STATE {
	WALKING_CASTLE = -2,
	IDLE = 5011,
	MOVE = 5010,
	JUMP = 5021,
	DOWN = 5021,
	ATTACK = 5030,
	ENTER = 5051,
	STAIRING = 5069,
	STAIRUP = 5070,
	STAIRDOWN = 5060,
	STAIRUP_ATTACK = 5080,
	JUMP_ATTACK = 5090,
	DOWN_ATTACK = 5100,
	DIE = 5111
};


enum DIRECTION {
	Left = -1,
	Right = 1
};

namespace AttackType {
	enum ATTACK_TYPE {
		HOLD = -999,
		THROW
	};
}
namespace TeamType {
	enum TYPE {
		LEAGUE,
		ENEMY,
		ITEM,
		GROUND,
		STATIC,
		WEAPON,
		STAIR,
		DOOR
	};
}

namespace Visual {
	enum FIGURES {
		NUM0 = 6351,
		NUM1,
		NUM2,
		NUM3,
		NUM4,
		NUM5,
		NUM6,
		NUM7,
		NUM8,
		NUM9
	};
}
namespace ObjectState {
	enum OBJ_STATE {
		ALIVE,
		BURN,
		ACTIVE_DAMAGE,
		DIE = 5111,
	};
}

namespace ObjectSpecial {
	enum OBJ_STAIR {
		STAIRUP_LTR = 6800,
		STAIRUP_RTL,
		STAIRDOWN_LTR,
		STAIRDOWN_RTL,
		STAIR_STOP
	};
	enum OBJ_DOOR {
		DOOR_IDLE = 6340,
		DOOR_OPEN_ACTIVE,
		DOOR_CLOSE_ACTIVE
	};
}

namespace ObjectEnemy {
	enum OBJ_BAT {
		OBJ_ENEMY_BAT_FLY = 6210,	//anim
		OBJ_ENEMY_BAT_SLEEP = 6211	// sprite
	};
	enum OBJ_DOG {
		OBJ_ENEMY_DOG_RUN = 6215,
		OBJ_ENEMY_DOG_IDLE = 6216,	//anim
		OBJ_ENEMY_DOG_JUMP = 6219
	};
	enum OBJ_FISHMAN {
		OBJ_ENEMY_FISHMAN_RUN = 6220,
		OBJ_ENEMY_FISHMAN_ATTACK = 6221,
		OBJ_ENEMY_FISHMAN_JUMP = 6223
	};
	enum OBJ_VAMPIREBAT {
		BOSS = 6344,
		OBJ_ENEMY_VAMPIREBAT_ATTACK = 6345,
		OBJ_ENEMY_VAMPIREBAT_IDLE = 6346,
		OBJ_ENEMY_VAMPIREBAT_FLY,
		OBJ_ENEMY_VAMPIREBAT_MOVETOSIDE
	};
}

namespace Anim {
	enum OBJ_ANIM {
		ANIM_BURN_EFFECT = 4056,
		ANIM_HOLLY_WATER_FLAME = 6167,
	};
}

enum OBJ_ID {
	OBJ_SIMON = -99,
	OBJ_WEAPON_WHIP = 6120,
	OBJ_WEAPON_WHIP1 = 6130,
	OBJ_WEAPON_WHIP2 = 6140,
	OBJ_WEAPON_WHIP3 = 6150,
	OBJ_SUBWEAPON_DAGGER = 6158,					 //id sprite
	OBJ_SUBWEAPON_AXE = 6160,					 // anim 
	OBJ_SUBWEAPON_HOLLYWATER = 6166,			//anim Holy
	OBJ_SUBWEAPON_BOOMERANG = 6170,				//anim
	OBJ_ENEMY_GHOST = 6200,						//anim
	OBJ_ENEMY_FIREBALL = 6225,					// spriteId
	OBJ_GROUND = -1,
	OBJ_ITEM_SUBWEAPON_NULL = -77,
	OBJ_ITEM_SMALLHEART = 4001,
	OBJ_ITEM_BIGHEART,
	OBJ_ITEM_MONEYBAG,
	OBJ_ITEM_MORNINGSTAR,
	OBJ_ITEM_DAGGER,
	OBJ_ITEM_CROSS,
	OBJ_ITEM_AXE,
	OBJ_ITEM_BOOMERANG,
	OBJ_ITEM_FIREBOMB,
	OBJ_ITEM_PORKCHOP,
	OBJ_ITEM_MAGICCRYSTAL,
	OBJ_STATIC_TORCH,
	OBJ_STATIC_CANDLE,
	OBJ_ITEM_STOPWATCH,
};

namespace Loader {
	enum OBJ_LOADED {
		BRICK = 0,
		BRICK2,
		BRICK3,
		BRICK_FLAG,
		BRICK_INTRO,
		CANDLE = 10,
		TORCH,
		DOOR = 20,
		STAIR = 30,
		GHOST,
		DOG,
		BAT,
		FISHMAN,

	};
}